### ISSUE TITLE
Cranberra error [fixed]

### ISSUE THREAD

**Issue by JordanMicahBennett** [SteveMacenski/jetson_nano_detection_and_tracking#16]
After going from flashing micro sd, to booting nano, to then installing everything via install.sh prepared by Steve, and when I finally wanted to do some inference/tests using his pre-organized coco model downloader and tensor rt converter aligned pb file, I stumbled upon an error at running the "python3 jetson_live_object_detection.py" (the same command for getting the basic object detection up and running with less than 2 arguments)

The error was a cranberra error, that was easily resolved using: "sudo-apt get install libcanberra-gtk-module".

See [the steps](https://github.com/JordanMicahBennett/live_ai_object-detection-on-tiny-jetson-neural-nano-computer/blob/master/README.md) I took to get this up and running (thanks to Steve's hard work).

**Comment by SteveMacenski** [comment]
Hi,

I see you closed this issue, did you find your problem?
