### ISSUE TITLE
Kalman Filter not integrated with the code

### ISSUE THREAD

**Issue by pranaysharma** [SteveMacenski/jetson_nano_detection_and_tracking#18]
Hi ,
Steve: First of all thanks for the easy installation script and great documentation!
I was reading the code and had two questions:

1.  It seems Kalman_filter.py is not linked/used by the code. Is this a mistake?
2.  Is there any specific reference that you used for the Kalman filter code? It will be great if you can share it

Thanks
Pranay

**Comment by SteveMacenski** [comment]
See #5
