### ISSUE TITLE
 No module named 'tf_trt_models.tf_trt_models'

### ISSUE THREAD

**Issue by kareemelzeftawy** [SteveMacenski/jetson_nano_detection_and_tracking#7]
Hello

I cloned your repository after that I executed the install script without any error
after that I executed  this python script:
 python3 tf_download_and_trt_model.py ssd_mobilenet_v2_coco

But I get this error:
 No module named 'tf_trt_models.tf_trt_models'

Can you help me, please!

**Comment by SteveMacenski** [comment]
did the install work without error? this would indicate the paths werent set up or you opened a new terminal without the updated bashrc file sourced

**Comment by kareemelzeftawy** [comment]
yes without error and I tried to open a new terminal now also the same reults

**Comment by SteveMacenski** [comment]
whats your PYTHONPATH

**Comment by kareemelzeftawy** [comment]
PYTHONPATH=$PYTHONPATH:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research/slim

**Comment by kareemelzeftawy** [comment]
![Capture](https://user-images.githubusercontent.com/14196470/58198395-6ddfc700-7cce-11e9-94a7-be781269cdc6.JPG)
![Capture1](https://user-images.githubusercontent.com/14196470/58198397-6ddfc700-7cce-11e9-8085-00f887afae7a.JPG)

**Comment by SteveMacenski** [comment]
What is the output of `echo $PYTHONPATH`. I know what the code says from your first comment, but I need to know if it actually took hold or not. If you didn't run with sudo it might be that the bashrc file wasnt modified. Also check that the path is indeed correct.

I've bootstrapped a couple nanos this way already so I'm surprised to see issues

**Comment by kareemelzeftawy** [comment]
/home/thingtrax/workspace/caffe:/home/thingtrax/workspace/caffe::/home/thingtrax/workspace/jetson_nano_detection_and_tracking:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/slim:/home/thingtrax/workspace/jetson_nano_detection_and_tracking:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/data:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research/slim:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research/slim:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research/slim:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research/slim:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research/slim:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research:/home/thingtrax/workspace/jetson$:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research/slim:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research/slim:/home/thingtrax/workspace/jetson_nano_detection_and_tracking/tf_trt_models/third_party/models/research:/home/thingtrax/workspace/jetson$

**Comment by SteveMacenski** [comment]
First off, you probably shouldn't have tried to install things that many times, you should clean up your environment. 
Second, assuming that path is valid and where you have placed it, this should work. Open a python terminal and start seeing where things are getting hung up. Unfortunately I can't fully just tell you what to do to fix it

**Comment by Tdoe4321** [comment]
So, I think it's actually a bug. I just tried to do it and I believe your import structure is messed up. 
To fix, you just need to change the following in tf_download_and_trt_model.py:
from "from tf_trt_models.tf_trt_models.detection import download_detection_model, build_detection_graph"
to "from tf_trt_models.detection import download_detection_model, build_detection_graph"

If that's hard to tell the difference, all you do it take off the first "tf_trt_models" from the import statement.

**Comment by SteveMacenski** [comment]
I'm curious then, where are you trying to run the script from? I suppose I have all my bash scripts on top of this go to the workspace prior -- perhaps this is when you're trying to run it while not in the same directory?

**Comment by Tdoe4321** [comment]
I've been running it from the root of your repo. The "jetson_nano_detection_and_tracking" directory.

**Comment by SteveMacenski** [comment]
Got it -- PRs are welcome. Not sure why its happy on my systems then but more than happy to resolve

**Comment by SteveMacenski** [comment]
#10 merged

**Comment by abouroubi** [comment]
Sorry to reopen the issue, but I think this PR messed things up, the import scripts were correct the first time.

The install script clone the repo "tf_trt_models" inside the working directory, and looking at the cloned repo the download_detection_model and build_detection_graph are in a nested directory with the same name "tf_trt_models", which gives us this file structure

```
$ PWD/tf_trt_models/tf_trt_models/detection.py
```

Changing back import statements to 
```Python
from tf_trt_models.tf_trt_models.detection import download_detection_model, build_detection_graph
```

did the trick for me, hope it helps

**Comment by Tdoe4321** [comment]
I actually saw the same behavior when I was doing development on my laptop. I don't understand it, but on the Nano, the single `tf_trt_models` worked, but on the laptop, it required two. My first thought was a python 2 vs 3 thing, but I don't know.

**Comment by SteveMacenski** [comment]
Feel free to open a PR!

**Comment by SteveMacenski** [comment]
@Tdoe4321 I just added a commit which will try to import the tf_trt_models then try that 2x.  That will let let it work in both cases, I hope that resolves!
